### PR TITLE
Add some Basic Functions

### PR DESCRIPTION
**Pull request by Yusarina**
I thought I would get some basic functions in, there are improvements needed, but everything seems to work just fine. 

- Added functions folder.
- Added Combine Materials (Basic and needs improvements.
- Added common file, this is where any common things that could be used by multiple functions will live.
- Clean materials, basic at the minute it cleans up material names in the given mesh by removing the '.001' suffix.
- Added fix UV Cords in which is in common, this should fix faulty uv coordinates, may need improvements as it's was the best way i could think of for the time being.
- Added join all meshes and selected meshes functions, this will use the fix uv cords while joining mehses. This is pretty basic as blender is quite good at doing the mesh joining itself. We may want to expand it in the future though.

### CODE REVIEW

**Comment by Yusarina** [comment]
@989onan Am I able to merge for now?

**Comment by 989onan** [comment]
this looks good for now yeah ^_^ We will fix any issues that come up during testing

**Comment by Yusarina** [comment]
There are some issues, such as you needing to select the armature for the options to work and not having a system to select which armature you want if you have multiple ones. But this can be fixed later.

**Comment by Yusarina** [comment]
See https://github.com/unofficalcats/Avatar-Toolkit/issues/20

**Pull request merged**
